#!/bin/bash
# 
# Purpose: GeoIP Update every Month, scheduling with crontab

GEOIP_MIRROR="http://geolite.maxmind.com/download/geoip/database"
GEOIPDIR=/usr/share/GeoIP
PIWIKDIR=/var/www/html/misc
TMPDIR=
DATABASES="GeoLiteCity GeoLiteCountry/GeoIP asnum/GeoIPASNum GeoIPv6"

if [ -d "${GEOIPDIR}" ]; then
        cd $GEOIPDIR
        if [ -n "${DATABASES}" ]; then
                TMPDIR=$(mktemp -d geoipupdate.XXXXXXXXXX)
                echo "Updating GeoIP databases..."
                for db in $DATABASES; do
                        fname=$(basename $db)
                        wget --no-verbose -t 3 -T 60 "${GEOIP_MIRROR}/${db}.dat.gz" -O "${TMPDIR}/${fname}.dat.gz"
                        gunzip -fdc "${TMPDIR}/${fname}.dat.gz" > "${TMPDIR}/${fname}.dat"
                        mv "${TMPDIR}/${fname}.dat" "${GEOIPDIR}/${fname}.dat"
                        chmod 0644 "${GEOIPDIR}/${fname}.dat"
                        cp "${GEOIPDIR}/${fname}.dat" $PIWIKDIR
                done
                [ -d "${TMPDIR}" ] && rm -rf $TMPDIR
        fi
fi
